### ISSUE TITLE
error: no bin target named `daemon`. 

### ISSUE THREAD

**Issue by alixanderthegreat** [Slixe/xelis-blockchain#3]
```
$ cargo run --bin daemon
error: no bin target named `daemon`.
Available bin targets:
    xelis_daemon
    xelis_miner
    xelis_wallet
```

Please correct README.md 
`cargo run --bin daemon`
To 
`cargo run --bin xelis_daemon`

**Comment by alixanderthegreat** [comment]
Cool project. Excited to keep testing.

**Comment by alixanderthegreat** [comment]
Oops. Following.

**Comment by Slixe** [comment]
Hey @alixanderthegreat,

Its already corrected in `dev` branch but I will write also that we can run it from main folder and just specify `--bin` too.
README.md is wrong because I've didn't updated it when I've merged the branch with the new sub projects created.

Thanks for reporting it.
